### ISSUE TITLE
Searching for term "git"

### ISSUE THREAD

**Issue by InSuperposition** [eirikb/nipster#2]
When searching for git related packages, the search returns all packages on github (I think). In any case the search is not specific enough.

**Comment by eirikb** [comment]
Yes, it's the standard datatables filter, and they way it is now it searches the td content as a whole. I think this can be fixed by adding a $.fn.dataTableExt.afnFiltering ( http://datatables.net/release-datatables/examples/plug-ins/range_filtering.html ). I'm not sure if it might help to add the links more properly as an alternative

**Comment by DTrejo** [comment]
+1 this was a problem for me today! I wanted to find a javascript git API thing, but couldn't :|

**Comment by eirikb** [comment]
According to this: http://datatables.net/examples/advanced_init/html_sort.html it should be built in to filter the tags out. I tried adding the class "html" to the th but it didn't help. I will look into it when I get home from work

**Comment by DTrejo** [comment]
thank you :)

**Comment by eirikb** [comment]
Is good?
It seems it didn't understand what the column is, perhaps since it's not a real element when it is handed over to DataTables. I had to set sType manually, then it just worked.

**Comment by eirikb** [comment]
This does not seem to work as it should, by searching for _git_ like this: http://eirikb.github.com/nipster/#git wrong package appears on top - and this seemingly because of "git" mentioned in href of author url.

I have set the author column as 'html', ref https://github.com/eirikb/nipster/commit/6ff4b7abc37087a2e67c457f23c084746cf51977, but it does not seem to reflect.
Any suggestion from anyone would be nice

**Comment by DTrejo** [comment]
Good luck :)
