### ISSUE TITLE
Description field renders HTML

### ISSUE THREAD

**Issue by kenany** [eirikb/nipster#20]
http://nipstr.com/#bluebird-lru-cache

In the above search result, the beginning of bluebird-lru-cache's `README.md`:

``` html
<a href="http://promisesaplus.com/">
    <img src="http://promisesaplus.com/assets/logo-small.png" alt="Promises/A+ logo" title="Promises/A+ 1.0 compliant" align="right" />
</a>
```

is being inserted into the `description` cell. Indeed, this HTML **is** the `description` of this module:

``` bash
$ npm info bluebird-lru-cache description
 </a><img src="http://promisesaplus.com/assets/logo-small.png" alt="Promises/A+ logo" title="Promises/A+ 1.0 compliant" align="right" />
```

but surely some sanitation must be done, right? Couldn't this lead to XSS attacks?

**Comment by eirikb** [comment]
I think this has been discussed before, and yes it is vulnerable to XSS. Since the page is static I'm not sure how much attacking you could do though, surely you can make the page halt or consume much cpu, or go to another page or throw up alot of alerts, but in the end not that much. Anyway, added a fix.
Author mail is still a danger, not sure if we need to fix that.
