### ISSUE TITLE
Fake duplicated packages.

### ISSUE THREAD

**Issue by TheHippo** [eirikb/nipster#4]
If I search for "coffee" the first package will be "pingdom-client" which, except for the author, has the same number of forks, watchers and even links to the coffee-script page are same. "coffee-script" itself is on the second place.

This looks more a like issue of the view then an error with the search.

**Comment by eirikb** [comment]
The reason for this is because the package is pointing to https://github.com/jashkenas/coffee-script , as you can see in http://search.npmjs.org/#/pingdom-client. I'm not sure what the best solution to this problem is. What I have done so far is to try contacting authors which are pointing to wrong repositories, and ask them to update the information. (It's also possible to fork and update, if one is able to locate the actual repository, although I have not had to do this).  
In this case I guess this is the supposed repository: https://github.com/tchype/node-pingdom-client

**Comment by eirikb** [comment]
Solved through issue https://github.com/tchype/node-pingdom-client/issues/1 . Will be updated on next run
